# Generated by Django 4.1.2 on 2023-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('pol', models.CharField(max_length=10, verbose_name='Пол')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=40, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пациента',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
