# Generated by Django 4.1.2 on 2023-03-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='aaa')),
            ],
        ),
        migrations.AlterField(
            model_name='registers',
            name='age',
            field=models.CharField(max_length=8, verbose_name='Возраст'),
        ),
    ]
